### ISSUE TITLE
vao required? :O

### ISSUE THREAD

**Issue by deus369** [theandrew168/sdl2-opengl-demo#1]
Hi sorry, working on Flecs + opengl game and realized this demo.. So i've been trying to get it to work with emscripten. And just realized vao isn't needed at all (and vertex arrays) for this example! It caused me a little pain trying to get it to work with WebGL 2.0 so I thought maybe it's best to remove it from the demo for new noobs in the future? :)

**Comment by theandrew168** [comment]
Hey, sorry for the delay! While this demo doesn't _require_ modern OpenGL features (namely VAOs), I wanted to use them here so that it would be up to date. I still use this as a reference when starting new OpenGL projects and am going to leave this code as-is. Appreciate the feedback, though!
